//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long user_id { get; set; }
        public Nullable<long> sn_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string access_token { get; set; }
        public string device_token_ios { get; set; }
        public string device_token_android { get; set; }
        public string profile_pic_url { get; set; }
        public Nullable<long> location_id { get; set; }
        public Nullable<float> current_location_longitude { get; set; }
        public Nullable<float> current_location_latitude { get; set; }
        public string college_name { get; set; }
        public Nullable<int> relationship_status { get; set; }
        public string current_work { get; set; }
        public Nullable<int> intrested_in { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string description { get; set; }
        public Nullable<bool> get_notifications { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
