//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_friends_heap
    {
        public long user_friends_heap_id { get; set; }
        public string sn_id { get; set; }
        public string sn_name { get; set; }
        public Nullable<long> user_id { get; set; }
    }
}
