//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_event
    {
        public long event_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string movie_url { get; set; }
        public string thumbnail_url { get; set; }
        public string video_title { get; set; }
        public Nullable<int> duration_time { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> status { get; set; }
    }
}
